config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
]

home/urls.py
from django.urls import path
from . import views



app_name = 'home'

urlpatterns = [
    path('room/new/', views.AddRoom.as_view(), name='add_view'),
    path('home/', views.AllRooms.as_view(), name='all_rooms'),
    path('home/room/del/<int:room_id>/', views.DeleteRoom.as_view(), name='del_room'),
    path('home/room/edit/<int:room_id>/', views.ModifyRoom.as_view(), name='edit_room'),
    path('home/room/mk_res/<int:room_id>/', views.BookRoom.as_view(), name='book_room'),
    path('home/room/<int:room_id>/', views.RoomDetails.as_view(), name='room_details'),
    path('home/search/', views.Search.as_view(), name='search'),
]

lrbs/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

home/models.py
from django.db import models

class Room(models.Model):
    name = models.CharField(max_length=255, unique=True)
    capacity = models.IntegerField(default=0)
    is_projector = models.BooleanField(default=False)

class Bookings(models.Model):
    room_id = models.ForeignKey(Room, on_delete=models.CASCADE, related_name='room_id')
    booking_date = models.DateField(blank=True, null=True)
    commentary = models.TextField(null=True)

    class Meta:
        unique_together = ('room_id', 'booking_date',)

home/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.http import HttpResponse
from home.models import Room, Bookings
import datetime


class AddRoom(View):
    """
    Adding a room to database.
    Checks if the room already exists and controls for proper input data.
    """
    def get(self, request):
        return render(request, 'home/add_room.html')

    def post(self, request):
        name = request.POST.get("name")
        if not name:
            return HttpResponse('Room name was empty')
        room_capacity = int(request.POST.get("room_capacity"))
        if not room_capacity or room_capacity < 1:
            return HttpResponse('Please indicate room capacity')
        is_projector = request.POST.get("is_projector")
        if is_projector == 'on':
            is_projector = True
        else:
            is_projector = False
        if Room.objects.filter(name=name):
            return HttpResponse('This room is already in database')

        Room.objects.create(name=name, capacity=room_capacity, is_projector=is_projector)
        return render(request, 'home/add_room.html')

class AllRooms(View):
    """
    Produces a view of all rooms.
    """
    def get(self, request):
        rooms = Room.objects.all().values()
        for room in rooms:
            booked = False
            reservations = Bookings.objects.filter(room_id_id=room['id'])
            reservation_dates = [res.booking_date for res in reservations]
            booked = datetime.date.today() in reservation_dates
        return render(request, 'home/all_rooms.html', {'rooms': rooms})

class DeleteRoom(View):
    """
    Deletes room from database.

    :param int room_id: id of the room
    """
    def get(self, request, room_id):
        room = Room.objects.get(pk=room_id)
        room.delete()
        rooms = Room.objects.all().values()
        return render(request, 'home/all_rooms.html', {'rooms': rooms})

class ModifyRoom(View):
    """
    Allows for modifying rooms (name, capacity, projector).
    Controls for proper input data.

    :param int room_id: id of the room
    """
    def get(self, request, room_id):
        room = Room.objects.get(pk=room_id)
        return render(request, 'home/edit.html', {'room': room})

    def post(self, request, room_id):
        room = Room.objects.get(pk=room_id)
        name = request.POST.get("name")
        if not name:
            return HttpResponse('Room name was empty')
        room_capacity = int(request.POST.get("room_capacity"))
        if not room_capacity or room_capacity < 1:
            return HttpResponse('Please indicate room capacity')
        is_projector = request.POST.get("is_projector")
        if is_projector == 'on':
            is_projector = True
        else:
            is_projector = False

        room.name = name
        room.capacity = room_capacity
        room.is_projector = is_projector
        room.save()

        return redirect('home:all_rooms')

class BookRoom(View):
    """
    Allows for making reservations.
    Checks if the room is already booked and if the requested date is in the future.

    :param int room_id: id of the room
    """
    def get(self, request, room_id):
        room = Room.objects.get(pk=room_id)
        reservations = Bookings.objects.filter(room_id_id=room_id).filter(
            booking_date__gte=str(datetime.date.today())).order_by('booking_date')
        return render(request, 'home/booking.html', {'room': room, 'reservations': reservations})

    def post(self, request, room_id):
        room = Room.objects.get(pk=room_id)
        room = room.id
        date = request.POST.get("date")
        comment = request.POST.get("comment")

        reservations = Bookings.objects.filter(room_id_id=room_id).filter(
            booking_date__gte=str(datetime.date.today())).order_by('booking_date')

        if Bookings.objects.filter(room_id_id=room, booking_date=date):
            return HttpResponse("This room is already booked for this date.")
        if date < str(datetime.date.today()):
            return HttpResponse("Please indicate future date for your reservation")

        Bookings.objects.create(room_id_id=room, booking_date=date, commentary=comment)
        return redirect('home:all_rooms')

class RoomDetails(View):
    """
    Produces detailed view for a particular room (features and reservations).

    :param int room_id: id of the room
    """
    def get(self, request, room_id):
        room = Room.objects.get(pk=room_id)
        reservations = Bookings.objects.filter(room_id_id=room_id).filter(booking_date__gte=str(datetime.date.today())).order_by('booking_date')
        return render(request, 'home/room_details.html', context={'room': room, 'reservations': reservations})

class Search(View):
    """
    Search engine for finding rooms with minimum expected capacity and projector availability.

    """
    def get(self, request):
        return render(request, 'home/search.html')

    def post(self, request):
        name = request.POST.get("name")
        room_capacity = int(request.POST.get("room_capacity"))
        if not room_capacity or room_capacity < 1:
            return HttpResponse('Please indicate real room capacity')
        is_projector = request.POST.get("is_projector")
        if is_projector == 'on':
            is_projector = True
        else:
            is_projector = False

        rooms = Room.objects.all().values()
        if is_projector:
            rooms = rooms.filter(is_projector=is_projector)
        if room_capacity:
            rooms = rooms.filter(room_capacity__gte=room_capacity)

        for room in rooms:
            reservations = Bookings.objects.filter(name=name).filter(
                booking_date__gte=str(datetime.date.today()))
            room.reserved = str(datetime.date.today()) in reservations

        return render(request, 'home/search.html', context={'rooms': rooms})

home/templates/home/add_room.html
{% extends 'base.html' %}

{% block container %}

  <form action="" method="POST">
  {% csrf_token %}
  <br><div>
  <label for="name">Room name:</label>
  <input type="text" id="name" name="name">
      </div><br>
      <div>
  <label for="room_capacity">Room capacity:</label>
  <input type="number" id="room_capacity" name="room_capacity">
          </div>
      <div><br>
  <label for="is_projector">Projector available</label>
  <input type="checkbox" id="is_projector" name="is_projector">
      </div><br>
      <div>
  <input type="submit" value="Add room to the database">
    </div>
</form>

{% endblock %}

home/templates/home/all_rooms.html
{% extends 'base.html' %}

{% block container %}
<div class="container-fluid">
        <table class="table">
            <thead class="thead-dark">
                <tr style="text-align: center">
                    <th scope="col">#</th>
                    <th scope="col">Room name</th>
                    <th scope="col">Details</th>
                    <th scope="col">Capacity</th>
                    <th scope="col">Availability</th>
                    <th scope="col">Projector</th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                {% for room in rooms %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ room.name }}</td>
                    <td style="text-align: center"><a href="room/{{ room.id }}/">&#128065;</a></td>
                    <td style="text-align: center">{{ room.capacity }}</td>
                        {% if booked %}
                    <td style="text-align: center">Booked</td>
                        {% else %}
                    <td style="text-align: center">Available</td>
                        {% endif %}
                        {% if room.is_projector %}
                    <td class="col-2" style="color:green; text-align: center">&#10004;</td>
                        {% else %}
                    <td class="col-2" style="color:red; text-align: center">&#10008;</td>
                        {% endif %}
                    <td><a href="room/edit/{{ room.id }}/">Edit</a></td>
                    <td><a href="room/del/{{ room.id }}/">Delete</a></td>
                    <td><a href="room/mk_res/{{ room.id }}/">Make reservation</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>


{% endblock %}

home/templates/home/booking.html
{% extends 'base.html' %}

{% block container %}

    <br>
    <h3>Make a reservation for {{ room.name }}:</h3>
    <br>

  <form action="" method="POST">
  {% csrf_token %}
      <br><div>
  <label for="date">Date:</label>
  <input type="date" id="date" name="date">
      </div><br>
      <div>
  <label for="comment">Comments:</label>
          <textarea id="comment" name="comment"> </textarea>
      </div>
      <div><br>
          <button type="submit" class="btn btn-primary" value="Make reservation">Make reservation</button>

    </div>
</form>

    <br>
    <br>
    <h3>Reservations:</h3>
    <br>
    <ul class="list-group">
      {% for reservation in reservations %}
      <li class="list-group-item">
        <h4>{{ reservation.booking_date }}</h4>
        <p>{{ reservation.commentary }}</p>
      </li>
      {% endfor %}

    </ul>

{% endblock %}

home/templates/home/edit.html
{% extends 'base.html' %}

{% block container %}

    <br>
    <h3>You are about to modify this room:</h3>
    <br>

    <div class="container-fluid">
        <table class="table">
            <thead class="thead-dark">
                <tr style="text-align: center">
                    <th scope="col">Room name</th>
                    <th scope="col">Capacity</th>
                    <th scope="col">Projector</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>{{ room.name }}</td>
                    <td style="text-align: center">{{ room.capacity }}</td>
                        {% if room.is_projector %}
                    <td class="col-2" style="color:green; text-align: center">&#10004;</td>
                        {% else %}
                    <td class="col-2" style="color:red; text-align: center">&#10008;</td>
                        {% endif %}
                </tr>
            </tbody>
        </table>
    </div>

    <br>
    <h3>Please enter modified features of the room:</h3>
    <br>

  <form action="" method="POST">
  {% csrf_token %}
  <br>
      <div class="form-group">
  <label for="name">Room name:</label>
  <input type="text" id="name" name="name">
      </div><br>
      <div>
  <label for="room_capacity">Room capacity:</label>
  <input type="number" id="room_capacity" name="room_capacity">
          </div>
      <div><br>
  <label for="is_projector">Projector available</label>
  <input type="checkbox" id="is_projector" name="is_projector">
      </div><br>
      <div>
  <input type="submit" class="btn btn-primary" value="Modify">
    </div>
</form>

{% endblock %}

home/templates/home/room_details.html
{% extends 'base.html' %}

{% block container %}

    <br>
    <h3>Detailed view of {{ room.name }}:</h3>
    <br>

<div class="container-fluid">
        <table class="table">
            <thead class="thead-dark">
                <tr style="text-align: center">
                    <th scope="col">Room name</th>
                    <th scope="col">Capacity</th>
                    <th scope="col">Availability</th>
                    <th scope="col">Projector</th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>{{ room.name }}</td>
                    <td style="text-align: center">{{ room.capacity }}</td>
                    <td style="text-align: center">Unknown</td>
                        {% if room.is_projector %}
                    <td class="col-2" style="color:green; text-align: center">&#10004;</td>
                        {% else %}
                    <td class="col-2" style="color:red; text-align: center">&#10008;</td>
                        {% endif %}
                    <td><a href="room/edit/{{ room.id }}/">Edit</a></td>
                    <td><a href="room/del/{{ room.id }}/">Delete</a></td>
                    <td><a href="room/mk_res/{{ room.id }}/">Make reservation</a></td>
                </tr>
            </tbody>
        </table>
    </div>

    <br>
    <h3>Reservations:</h3>
    <br>

    <div class="container-fluid">
        <table class="table">
            <thead class="thead-dark">
                <tr style="text-align: left">
                    <th scope="col">#</th>
                    <th scope="col">Date</th>
                    <th scope="col">Commentary</th>
                </tr>
            </thead>
            <tbody>
                {% for res in reservations %}
                <tr style="text-align: left">
                    <td>{{ forloop.counter }}</td>
                    <td>{{ res.booking_date }}</td>
                    <td>{{ res.commentary }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

{% endblock %}

home/templates/home/search.html
{% extends 'base.html' %}

{% block container %}

    <h3>Search</h3>

<div class="card">

  <div class="card-body">

    <form action="" method="GET">
      {% csrf_token %}
      <div class="form-group">
        <label for="capacity">Minimum capacity</label>
        <input type="number" step="1" class="form-control" id="capacity" placeholder="10" name="capacity">
      </div>
      <div class="form-check">
        <input type="checkbox" class="form-check-input" name="projector" id="projector">
        <label class="form-check-label" for="projector">Projector</label>
      </div>
      <button type="submit" class="btn btn-primary">Search</button>
    </form>
  </div>
</div>

<div class="container-fluid">
        <table class="table">
            <thead class="thead-dark">
                <tr style="text-align: center">
                    <th scope="col">#</th>
                    <th scope="col">Room name</th>
                    <th scope="col">Details</th>
                    <th scope="col">Capacity</th>
                    <th scope="col">Availability</th>
                    <th scope="col">Projector</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                {% for room in rooms %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ room.name }}</td>
                    <td style="text-align: center"><a href="room/{{ room.id }}/">&#128065;</a></td>
                    <td style="text-align: center">{{ room.room_capacity }}</td>
                        {% if booked %}
                    <td style="text-align: center">Booked</td>
                        {% else %}
                    <td style="text-align: center">Available</td>
                        {% endif %}
                        {% if room.is_projector %}
                    <td class="col-2" style="color:green; text-align: center">&#10004;</td>
                        {% else %}
                    <td class="col-2" style="color:red; text-align: center">&#10008;</td>
                        {% endif %}
                    <td><a href="room/mk_res/{{ room.id }}/">Make reservation</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>


{% endblock %}

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Lecture Room Booking System</title>
    <link rel="stylesheet" href="{% static 'styles/bootstrap.min.css' %}" type="text/css" media="screen">
    <script src="{% static 'scripts/bootstrap.min.js' %}" async defer></script>

    {% include 'partials/styles.html' %}

</head>

<body>

<!-- NAVIGATION BAR -->
{% include 'partials/nav.html' %}

<!-- CONTAINERS -->

    <div class="container mt-3">
        <div class="row">
            <div class="col">


{% block container %}

{% endblock %}

            </div>
        </div>
    </div>

<!-- FOOTER -->
 <footer class="footer">
  <p>Created by S.Cz.</p>
  <p><a href="mailto:slaw.czech@gmail.com">Contact me</a></p>
</footer>
</body>
</html>

templates/partials/nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
    <a class="navbar-brand">Book-A-Room!</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'home:all_rooms' %}">Room list</a>
        </li>
          <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'home:add_view' %}">Add room</a>
        </li>
          <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'home:search' %}">Search for a room</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

templates/partials/styles.html
<style>
    .footer {
        text-align: center;
        position: absolute;
        width: 100%;
        bottom: 0;
        color: #bacbe6;
    }

    a:link, a:visited {
        text-decoration: none;
        color: #bacbe6;
    }

    a:hover {
        color: #0a53be;
    }

</style>